export const PRODUCT_ENGAGEMENT_BADGE_CONFIG = {
  windowDays: 30,
  bestSellerEnabled: true,
  bestSellerUnitsThreshold: 8,
  bestSellerIcon: "trophy",
  bestSellerIconUrl: "",
  bestSellerColor: "green",
  bestSellerBackgroundColor: "#1a8553",
  bestSellerForegroundColor: "#ffffff",
  popularEnabled: true,
  popularClicksThreshold: 10,
  popularIcon: "cursor",
  popularIconUrl: "",
  popularColor: "blue",
  popularBackgroundColor: "#145af2",
  popularForegroundColor: "#ffffff",
  trendingNowEnabled: true,
  trendingNowUnitsThreshold: 4,
  trendingNowGrowthMultiplier: 1.5,
  trendingNowIcon: "trend",
  trendingNowIconUrl: "",
  trendingNowColor: "slate",
  trendingNowBackgroundColor: "#596579",
  trendingNowForegroundColor: "#ffffff",
  risingStarEnabled: true,
  risingStarScoreThreshold: 20,
  risingStarClickThreshold: 4,
  risingStarIcon: "spark",
  risingStarIconUrl: "",
  risingStarColor: "amber",
  risingStarBackgroundColor: "#ff7a18",
  risingStarForegroundColor: "#ffffff",
} as const;

export type ProductEngagementBadgeKey = "best_seller" | "popular" | "trending_now" | "rising_star";
